# Generated by Django 2.1 on 2019-01-17 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('misioncooperativa', models.CharField(blank=True, help_text='Ingrese la Mision de la Cooperativa', max_length=255, verbose_name='Mision de la Cooperativa')),
                ('visioncooperativa', models.CharField(blank=True, help_text='Ingrese la Vision de la Cooperativa', max_length=255, verbose_name='Vision de la Cooperativa')),
                ('logocooperativa', models.ImageField(blank=True, null=True, upload_to='static/photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombredepartamentos', models.CharField(blank=True, help_text='Ingrese su Nombre de Departamento', max_length=50, null=True, unique=True, verbose_name='Departamento')),
                ('sigladepartamentos', models.CharField(blank=True, help_text='Ingrese la Sigla de Departamento', max_length=15, null=True, verbose_name='Sigla del Departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombredirecciones', models.CharField(help_text='Ingrese Nombre de la Direcciones', max_length=50, verbose_name='Nombre de la Direcciones')),
                ('sigladirecciones', models.CharField(blank=True, help_text='Ingrese la Sigla de la Direcciones', max_length=15, null=True, verbose_name='Sigla de la Direcciones')),
                ('descripciondirecciones', models.CharField(blank=True, help_text='Ingrese la Descripcion de la Direcciones', max_length=255, null=True, verbose_name='Descripcion de la Direcciones')),
                ('estadodirecciones', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombreinstituciones', models.CharField(help_text='Ingrese su Nombre Institucion', max_length=50, null=True, verbose_name='Nombre Institucion')),
                ('siglainstituciones', models.CharField(blank=True, help_text='Ingrese la Sigla Institucion', max_length=15, null=True, verbose_name='Sigla Institucion')),
                ('nitinstituciones', models.CharField(help_text='Ingrese el Nit o Número de Identifican Tributaria', max_length=20, unique=True, verbose_name='Nit de Institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombremunicipios', models.CharField(blank=True, help_text='Ingrese su Nombre Ciudad', max_length=50, null=True, verbose_name='Ciudad')),
                ('siglamunicipios', models.CharField(blank=True, help_text='Ingrese la Sigla Ciudad', max_length=15, null=True, verbose_name='Sigla Ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planservicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombreplanservicios', models.CharField(help_text='Ingrese Nombre del Servicio', max_length=50, verbose_name='Nombre del Servicio')),
                ('detalleplanservicios', models.CharField(blank=True, help_text='Ingrese Detalle del Plan Servicio', max_length=255, null=True, verbose_name='Detalle del Plan Servicio')),
                ('estadoplanservicios', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Precioservicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('costoprecioservicios', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ingrese su Valor', max_digits=50, null=True, verbose_name='Valor')),
                ('monedaprecioservicios', models.CharField(choices=[('BS', 'Bolivianos'), ('R$', 'Reales'), ('USD', 'Dolares')], default='BS', help_text='Ingrese Tipo Moneda', max_length=5, verbose_name='Moneda')),
                ('estadoprecioservicios', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombreprovincias', models.CharField(blank=True, help_text='Ingrese su Nombre Provinvia', max_length=50, null=True, unique=True, verbose_name='Provinvia')),
                ('siglaprovincias', models.CharField(blank=True, help_text='Ingrese la Sigla Provinvia', max_length=15, null=True, verbose_name='Sigla Provinvia')),
                ('Departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Departamentos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombreservicios', models.CharField(help_text='Ingrese Nombre del Servicio Servicio', max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener caracteres alfanúmericos', regex='^[[0-9a-zA-Z]||[ñÑ]]*$')], verbose_name='Nombre del Servicio')),
                ('siglaservicios', models.CharField(help_text='Ingrese la Sigla del Servicio', max_length=20, verbose_name='Sigla del Servicio')),
                ('descripcionservicios', models.CharField(blank=True, help_text='Ingrese Descripcion del Servicio', max_length=50, null=True, verbose_name='Descripcion del Servicio')),
                ('estadoservicios', models.BooleanField(default=True)),
                ('Cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subunidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombresubunidades', models.CharField(blank=True, help_text='Ingrese Nombre de la Subunidad', max_length=50, null=True, verbose_name='Nombre de la Subunidad')),
                ('siglasubunidades', models.CharField(blank=True, help_text='Ingrese la Subunidad', max_length=15, null=True, verbose_name='Sigla de la Subunidad')),
                ('descripcionsubunidades', models.CharField(blank=True, help_text='Ingrese la Descripcion de la Subunidad', max_length=255, null=True, verbose_name='Descripcion de la Subunidad')),
                ('estadosubunidades', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombreunidades', models.CharField(blank=True, help_text='Ingrese Nombre de la Unidad', max_length=50, null=True, verbose_name='Nombre de la Unidad')),
                ('siglaunidades', models.CharField(blank=True, help_text='Ingrese la Unidad', max_length=15, null=True, verbose_name='Sigla de la Unidades')),
                ('descripcionunidades', models.CharField(blank=True, help_text='Ingrese la Descripcion de la Unidad', max_length=255, null=True, verbose_name='Descripcion de la Unidad')),
                ('estadounidades', models.BooleanField(default=True)),
                ('Direcciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Direcciones')),
                ('Unidades_Subunidades', models.ManyToManyField(to='cooperativa.Subunidades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planservicios',
            name='Precioservicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Precioservicios'),
        ),
        migrations.AddField(
            model_name='planservicios',
            name='Servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Servicios'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='Provincias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Provincias'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='Instituciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Instituciones'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='Municipios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Municipios'),
        ),
    ]
