# Generated by Django 2.1 on 2019-01-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativa', '0001_initial'),
        ('geolocalizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombrebarrio', models.CharField(blank=True, help_text='Ingrese Nombre del Barrio', max_length=50, null=True, unique=True, verbose_name='Nombre del Barrio')),
                ('siglabarrio', models.CharField(blank=True, help_text='Ingrese Sigla del Barrio', max_length=20, null=True, verbose_name='Sigla del Barrio')),
                ('detallebarrio', models.CharField(blank=True, help_text='Ingrese Detalle del Barrio', max_length=255, null=True, verbose_name='Detalle del Barrio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('celularcliente', models.CharField(blank=True, help_text='Ingrese el Numero de Celular', max_length=15, null=True, verbose_name='Numero de Celular')),
                ('emailcliente', models.CharField(blank=True, help_text='Ingrese el Email', max_length=50, null=True, verbose_name='Email')),
                ('observacioncliente', models.CharField(blank=True, help_text='Ingrese Observaciones', max_length=50, null=True, verbose_name='Observaciones')),
                ('estadocliente', models.BooleanField(default=True)),
                ('usuariocliente', models.IntegerField(blank=True, null=True)),
                ('Instituciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Instituciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('zonadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Zona', max_length=50, null=True, verbose_name='Zona')),
                ('referenciadireccion', models.CharField(blank=True, help_text='Ingrese Referencia', max_length=50, null=True, verbose_name='Referencia')),
                ('viadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Via', max_length=50, null=True, verbose_name='Nombre de la Via')),
                ('calledireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Calle', max_length=50, null=True, verbose_name='Nombre de la Calle')),
                ('numerocasadireccion', models.CharField(blank=True, help_text='Ingrese Numero de Casa', max_length=20, null=True, verbose_name='Numero de Casa')),
                ('avenidadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Avenida', max_length=50, null=True, verbose_name='Nombre de la Avenida')),
                ('Barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Barrio')),
                ('Ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.Ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numerodistrito', models.IntegerField(blank=True, help_text='Ingrese el Numero del Distrito', null=True, verbose_name='Numero del Distrito')),
                ('nombredistrito', models.CharField(blank=True, help_text='Ingrese del Nombre Distrito', max_length=50, null=True, verbose_name='Nombre Distrito')),
                ('sigladistrito', models.CharField(blank=True, default='Sin/Sigla', help_text='Ingrese la Sigla del Distrito', max_length=10, null=True, verbose_name='Sigla del Distrito')),
                ('detalledistrito', models.CharField(blank=True, help_text='Ingrese Detalle del Distrito', max_length=255, null=True, verbose_name='Detalle del Distrito')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombrepersona', models.CharField(help_text='Ingrese su Nombre', max_length=100, null=True, verbose_name='Nombre')),
                ('paternopersona', models.CharField(blank=True, help_text='Ingrese su Apellido Paterno', max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('maternopersona', models.CharField(blank=True, help_text='Ingrese su Apellido Materno', max_length=100, null=True, verbose_name='Apellido Materno')),
                ('cipersona', models.CharField(help_text='Ingrese su Numero de Cedula de Identidad', max_length=20, null=True, unique=True, verbose_name='Cedula de Identidad')),
                ('generopersona', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Ingrese Genero', max_length=1, verbose_name='Genero')),
                ('nacimientopersona', models.DateField(blank=True, help_text='Seleccione su fecha de nacimiento', null=True, verbose_name='Fecha de nacimiento')),
                ('usuariopersona', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='Personas_Clientes',
            field=models.ManyToManyField(to='clientes.Persona'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='Distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Distrito'),
        ),
    ]
